global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'fastapi-app'
    metrics_path: /metrics
    static_configs:
      - targets: ['app:8000']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
